# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024 Intel Corporation

go-mod: FORCE
	(cd asciichart; go mod tidy)
	(cd cfg; go mod tidy)
	(cd colorize; go mod tidy)
	(cd configview; go mod tidy)
	(cd constants; go mod tidy)
	(cd cpudata; go mod tidy)
	(cd dbg; go mod tidy)
	(cd devbind; go mod tidy)
	(cd etimers; go mod tidy)
	(cd fserde; go mod tidy)
	(cd graphdata; go mod tidy)
	(cd helpers; go mod tidy)
	(cd hexdump; go mod tidy)
	(cd meter; go mod tidy)
	(cd pcap; go mod tidy)
	(cd perfview; go mod tidy)
	(cd portinfo; go mod tidy)
	(cd statsview; go mod tidy)
	(cd taborder; go mod tidy)
	(cd ttylog; go mod tidy)
	(cd vpanels; go mod tidy)

FORCE:
